http://localhost:8000 

###
POST http://localhost:8000/webhook/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyX3ByZSI6ImN3ZWItIiwicl9zdWYiOiIiLCJwZyI6dHJ1ZSwicF9icmFuIjpudWxsLCJyZXBvIjoiaG9uZXN0YmVlL2N3ZWIiLCJpc3MiOiJkYXZ5LWpvbmVzIiwiaWF0IjoiMjAxOS0wNi0wNVQxMzozNzowNi40MjYyOTQzNjdaIiwiaGRfc2VjciI6IjJ3c3gifQ.STZqBeB7LdHvhwvGVxrNLuH1nlsfeJtiLtLYbG1fuHE  http/1.1
content-type: application/json

{
  "ref": "test",
  "ref_type": "branch",
  "repository": {
    "full_name": "honestbee/cweb"
  }
}

###
POST http://localhost:8000/webhook http/1.1
content-type: application/json

{
  "release_name_prefix": "cweb-",
  "release_name_suffix": "",
  "purge": true,
  "protected_branch_name": null,
  "repository_name": "honestbee/cweb",
  "webhook_secret": "2wsx"
}