version: '3.7'
services:
  davy-jones-dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    env_file: ./.env
    entrypoint: cargo watch -w src/ -x "run --features 'production'"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
