apiVersion: v1
clusters:
- cluster:
    server: {{ api_server }}
  name: helm
contexts:
- context:
    cluster: helm
    namespace: {{ namespace }}
    user: helm
  name: helm
current-context: "helm"
kind: Config
preferences: {}
users:
- name: helm
  user:
    token: {{ token }}
